# image will be published to ghcr.io/<user>/<name>
name: cabos-cinnamon-asus
# description will be included in the image's metadata
description: A hyper opinionated Fedora Silverblue spin aimed at creators

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/legacy-images/cinnamon-asus
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common_modules/signing.yml
  - from-file: common_modules/asus-akmods.yml
  - from-file: common_modules/files.yml
  - from-file: common_modules/rpm-ostree.yml
  - from-file: common_modules/rpm-ostree-cinnamon.yml
  - from-file: common_modules/rpm-ostree-rm-nvtop.yml
  - from-file: common_modules/bling.yml
  - from-file: common_modules/fonts.yml
  - from-file: common_modules/yafti.yml
  - from-file: common_modules/default-flatpaks.yml
  - from-file: common_modules/skel.yml
  - from-file: common_modules/scripts.yml
  - from-file: common_modules/systemd.yml