type: akmods
install:
    - v4l2loopback
    - xone
    - xpadneo
    - xpad-noone
    - winesync

type: files
files:
  - usr: /usr
  - etc: /etc

type: initramfs-setup
include:
  - /etc/crypttab
  - /etc/vconsole.conf
  - /etc/modprobe.d/modprobe-gidro.conf

type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/szydell/system76/repo/fedora-%OS_VERSION%/szydell-system76-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo

install:
  - gnome-shell-extension-caffeine
  - system76-scheduler
  - gnome-shell-extension-system76-scheduler
  - system76-power
  - android-tools
  - nerd-fonts
  - zsh
  - gnome-boxes
  - code
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - containerd.io
  - p7zip
  - p7zip-plugins
  - podman-compose
  - podman-plugins
  - podman-tui
  - podmansh
  - playerctl
  - nautilus-gsconnect
  - gnome-shell-extension-gsconnect
  - python3-pip
  - samba
  - samba-dcerpc
  - samba-ldb-ldap-modules
  - samba-winbind-clients
  - samba-winbind-modules
  - konsole
  - libvirt

remove:
  - firefox
  - firefox-langpacks
  - htop
  - nvtop
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-initial-setup
  - gnome-system-monitor
  - gnome-classic-session
  - gnome-extensions-app

type: bling
install:
  - dconf-update-service
  - ublue-os-wallpapers
  - ublue-update
  - container-tools

type: yafti
custom-flatpaks:

type: default-flatpaks
notify: true
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub-system
  repo-title: "Flathub (System)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
  install:
    - org.gnome.Calculator
    - org.gnome.Calendar
    - org.gnome.Snapshot
    - org.gnome.Contacts
    - org.gnome.clocks
    - org.gnome.Evince
    - org.gnome.Maps
    - org.gnome.TextEditor
    - com.github.neithern.g4music
    - com.github.rafostar.Clapper
    - org.gnome.Loupe
    - io.missioncenter.MissionCenter
    - com.vixalien.sticky
    - com.github.tchx84.Flatseal
    - io.github.fabrialberio.pinapp
    - com.mattjakeman.ExtensionManager
    - io.podman_desktop.PodmanDesktop
    - com.uploadedlobster.peek
    - org.mozilla.firefox
user:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub-user
  repo-title: "Flathub"

type: systemd
system:
  enabled:
    - initramfs-setup.service
    - minimum-free-zram.service
    - com.system76.PowerDaemon.service
    - system76-power-wake.service
    - com.system76.Scheduler.service
  masked:
    - power-profiles-daemon.service
user:
  enabled:
    - podman.socket
    - docker.socket

type: script
scripts:
  - system76-scheduler.sh
  - signing.sh