type: default-flatpaks
notify: true
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub-system
  repo-title: "Flathub (System)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
  install:
    - org.gnome.Calculator
    - org.gnome.Calendar
    - org.gnome.Snapshot
    - org.gnome.Contacts
    - org.gnome.clocks
    - org.gnome.Evince
    - org.gnome.TextEditor
    - org.gnome.Loupe
    - com.github.neithern.g4music
    - com.github.rafostar.Clapper
    - io.missioncenter.MissionCenter
    - com.vixalien.sticky
    - com.github.tchx84.Flatseal
    - io.github.fabrialberio.pinapp
    - com.mattjakeman.ExtensionManager
    - sa.sy.bluerecorder
    - org.mozilla.firefox
    - it.mijorus.gearlever
user:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub-user
  repo-title: "Flathub"
