type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/szydell/system76/repo/fedora-%OS_VERSION%/szydell-system76-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/prompt/repo/fedora-%OS_VERSION%/kylegospo-prompt-fedora-%OS_VERSION%.repo

install:
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-system76-scheduler
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-dash-to-panel
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-appindicator
  - system76-scheduler
  - system76-power
  - android-tools
  - nerd-fonts
  - zsh
  - gnome-boxes
  - code
  - prompt
  - vte291
  - vte-profile
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - containerd.io
  - p7zip
  - p7zip-plugins
  - podman-compose
  - podman-plugins
  - podman-tui
  - podmansh
  - playerctl
  - nautilus-gsconnect
  - python3-pip
  - samba
  - samba-dcerpc
  - samba-ldb-ldap-modules
  - samba-winbind-clients
  - samba-winbind-modules
  - libvirt

remove:
  - firefox
  - firefox-langpacks
  - htop
  - nvtop
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-initial-setup
  - gnome-system-monitor
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-shell-extension-background-logo
  - gnome-classic-session
  - gnome-terminal
  - gnome-terminal-nautilus