type: rpm-ostree

install:
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-system76-scheduler
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-dash-to-panel
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-appindicator

remove:
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-initial-setup
  - gnome-system-monitor
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-shell-extension-background-logo
  - gnome-classic-session