type: systemd
system:
  enabled:
    - minimum-free-zram.service
    - com.system76.PowerDaemon.service
    - system76-power-wake.service
    - com.system76.Scheduler.service
    - dx-groups.service
  masked:
    - power-profiles-daemon.service
user:
  enabled:
    - podman.socket
    - docker.socket
    - dx-user-vscode.service
    - dx-user-gsettings.service
