name: bluebuild
on:
  schedule:
    - cron: "00 17 * * *" # build at 17:00 UTC every day
                          # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          # - recipe-cinnamon-39.yml
          # - recipe-cinnamon-40.yml
          # - recipe-cinnamon-nvidia-39.yml
          # - recipe-cinnamon-nvidia-40.yml
          # - recipe-cinnamon-asus-39.yml
          # - recipe-cinnamon-asus-40.yml
          # - recipe-cinnamon-asus-nvidia-39.yml
          # - recipe-cinnamon-asus-nvidia-40.yml
          # - recipe-cinnamon-surface-39.yml
          # - recipe-cinnamon-surface-40.yml
          # - recipe-cinnamon-surface-nvidia-39.yml
          # - recipe-cinnamon-surface-nvidia-40.yml
          # - recipe-gnome-39.yml
          # - recipe-gnome-40.yml
          - recipe-gnome-41.yml
          # - recipe-gnome-nvidia-39.yml
          # - recipe-gnome-nvidia-40.yml
          # - recipe-gnome-asus-39.yml
          # - recipe-gnome-asus-40.yml
          # - recipe-gnome-asus-nvidia-39.yml
          # - recipe-gnome-asus-nvidia-40.yml
          # - recipe-gnome-surface-39.yml
          # - recipe-gnome-surface-40.yml
          # - recipe-gnome-surface-nvidia-39.yml
          # - recipe-gnome-surface-nvidia-40.yml
    steps:
       # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
